# Generated by Django 5.2 on 2025-04-15 15:27

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relampagoweb", "0002_configuracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
