# Generated by Django 5.2 on 2025-06-08 05:24

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0004_pedido_usar_descuento_alter_pedido_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usar_descuento',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
