# Generated by Django 5.2 on 2025-06-08 05:31

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0006_pedido_usar_descuento_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='compra_tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
