# Generated by Django 5.2 on 2025-06-12 21:12

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0007_lineapedido_compra_tipo_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_camiseta_sola',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coste unitario de la camiseta suelta (si procede)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_equipacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
