# Generated by Django 5.2 on 2025-06-12 17:29

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0007_lineapedido_compra_tipo_alter_pedido_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='jugadores/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en la galería')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
