# Generated by Django 5.2 on 2025-06-12 21:14

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0008_lineapedido_costo_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='costo_equipacion',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
