# Generated by Django 5.2 on 2025-06-12 21:44

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0009_remove_producto_costo_equipacion_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_camiseta_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coste unitario de la camiseta suelta con descuento (si procede)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
