# Generated by Django 5.2 on 2025-06-12 22:00

import shortuuid.main
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0010_producto_costo_camiseta_descuento_alter_pedido_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='costo_camiseta_descuento',
            new_name='precio_camiseta_descuento',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='costo_camiseta_sola',
            new_name='precio_camiseta_sola',
        ),
        migrations.AddField(
            model_name='producto',
            name='coste_provedor_completa',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('22.00'), help_text='Precio que pagamos al proveedor por la equipación completa (camiseta)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
