# Generated by Django 5.2 on 2025-06-12 22:06

import shortuuid.main
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0012_producto_coste_provedor_camiseta_alter_pedido_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='coste_provedor_completa',
        ),
        migrations.AddField(
            model_name='producto',
            name='coste_provedor',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('35.00'), help_text='Precio que pagamos al proveedor por el producto, usar para equipaciones completas y sudaderas', max_digits=6),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
