# Generated by Django 5.2 on 2025-06-12 22:07

import shortuuid.main
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0013_remove_producto_coste_provedor_completa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='coste_provedor_camiseta',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('22.00'), help_text='Precio que pagamos al proveedor por la equipación solo camiseta', max_digits=6),
        ),
    ]
