# Generated by Django 5.2 on 2025-06-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0009_alter_pedido_id'),
        ('relampagoweb', '0015_alter_pedido_id_and_more'),
    ]

    operations = [
    ]
