# Generated by Django 5.2 on 2025-06-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relampagoweb', '0016_merge_20250613_0126'),
        ('relampagoweb', '0018_alter_pedido_id'),
    ]

    operations = [
    ]
